import "../tailwind.css";
import type { Metadata } from "next";
import Navigation from "./navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="flex flex-row h-screen w-full bg-darkMyt-100 text-lightMyt-100">
        <Navigation />
        <div className="flex flex-nowrap content-around items-center gap-20 w-full h-min justify-start pt-20 px-12">
          <div className="flex justify-center w-full">
            <div className="flex w-full justify-start max-w-5xl">
              {" "}
              {children}{" "}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
